# Generated by Django 4.0.4 on 2022-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_rename_firstname_detailuser_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='replyto',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailuser',
            name='addressLine1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailuser',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailuser',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailuser',
            name='contactNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailuser',
            name='registrationNumber',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
