# Generated by Django 4.0.4 on 2022-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0003_directmessage_replyto_directmessage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
