# Generated by Django 4.0.4 on 2022-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0004_directmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='dropX',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='load',
            name='dropY',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='load',
            name='pickX',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='load',
            name='pickY',
            field=models.FloatField(default=0),
        ),
    ]
